# Generated by Django 5.0 on 2025-05-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='care_tips',
            field=models.TextField(blank=True, help_text='General care instructions and tips for growing this crop', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='fertilizers',
            field=models.TextField(blank=True, help_text='Recommended fertilizers and application guidelines', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='pesticides',
            field=models.TextField(blank=True, help_text='Recommended pesticides and application guidelines', null=True),
        ),
    ]
