# Generated by Django 5.0 on 2025-05-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(choices=[('None', 'No Certification'), ('Organic', 'Organic Certified'), ('GAP', 'Good Agricultural Practices'), ('Fairtrade', 'Fairtrade Certified')], default='None', help_text='Product certification type', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_available',
            field=models.BooleanField(default=False, help_text='Whether delivery service is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Minimum quantity that can be ordered', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('mesh', 'Mesh Bag'), ('carton', 'Carton Box'), ('none', 'No Packaging')], default='none', help_text='Type of packaging used', max_length=20),
        ),
    ]
