# Generated by Django 5.0 on 2025-05-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='farmerprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_farmer_profile'),
        ),
    ]
