# Generated by Django 5.0 on 2025-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farmerprofile_unique_farmer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
