# Generated by Django 5.0 on 2025-08-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_buyerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
