from django.core.management.base import BaseCommand
from django.db import transaction
from django.core.files import File
from django.core.files.storage import default_storage   
from django.conf import settings
from crops.models import Crop

class Command(BaseCommand):
    help = 'Initialize crops database with default values'

    def handle(self, *args, **options):
        # Crops data dictionary
        crops_data = [
            {
                "name": "banana",
                "description": "A tropical fruit crop rich in potassium and essential vitamins, grown in humid climates.",
                "image": "crops/banana.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 30.0,
                "growing_time": 9,
                "min_temperature": 15.0,
                "max_temperature": 35.0,
                "min_rainfall": 1200,
                "max_rainfall": 2500,
                "min_nitrogen": 200,
                "max_nitrogen": 300,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 300,
                "max_potassium": 500,
                "min_ph": 5.5,
                "max_ph": 7.0,
                "care_tips": "Requires regular watering, protection from strong winds, and mulching.",
                "fertilizers": "NPK 8-10-12 + magnesium, apply 200g/plant every 2 months",
                "pesticides": "Imidacloprid for aphids, Carbofuran for nematodes, Beauveria bassiana for weevils"
            },
            {
                "name": "barley",
                "description": "A versatile cereal grain used for food, animal feed, and brewing beer, tolerant to dry climates.",
                "image": "crops/barley.jpg",
                "growing_season": "Winter in mild climates",
                "average_yield": 3.0,
                "growing_time": 4,
                "min_temperature": 4.0,
                "max_temperature": 30.0,
                "min_rainfall": 300,
                "max_rainfall": 800,
                "min_nitrogen": 80,
                "max_nitrogen": 120,
                "min_phosphorus": 20,
                "max_phosphorus": 40,
                "min_potassium": 50,
                "max_potassium": 100,
                "min_ph": 6.0,
                "max_ph": 8.5,
                "care_tips": "Plant in well-drained soil, avoid excessive nitrogen.",
                "fertilizers": "DAP at sowing (100kg/ha), Urea top dressing (50kg/ha)",
                "pesticides": "Propiconazole for rust, Chlorpyrifos for aphids"
            },
            {
                "name": "bittergourd",
                "description": "A medicinal vegetable with a bitter taste, known for its benefits in managing blood sugar levels.",
                "image": "crops/bittergourd.jpg",
                "growing_season": "Summer",
                "average_yield": 10.0,
                "growing_time": 3,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 600,
                "max_rainfall": 1500,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 80,
                "max_potassium": 120,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Needs trellising, regular harvesting encourages more fruit.",
                "fertilizers": "Vermicompost (5kg/sq.m) + NPK 10-10-10 (50g/plant)",
                "pesticides": "Neem oil for fruit flies, Spinosad for beetles"
            },
            {
                "name": "blackgram",
                "description": "A protein-rich legume widely used in South Asian cuisine, especially for dals and curries.",
                "image": "crops/blackgram.jpg",
                "growing_season": "Kharif/Rainy season",
                "average_yield": 0.8,
                "growing_time": 3,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 600,
                "max_rainfall": 1000,
                "min_nitrogen": 20,
                "max_nitrogen": 40,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 20,
                "max_potassium": 40,
                "min_ph": 6.5,
                "max_ph": 7.5,
                "care_tips": "Drought tolerant but needs irrigation at flowering stage.",
                "fertilizers": "Rhizobium inoculation, SSP (250kg/ha)",
                "pesticides": "Carbendazim for root rot, Dimethoate for whiteflies"
            },
            {
                "name": "blackpepper",
                "description": "A highly prized spice known as the 'King of Spices', used globally for its pungent flavor.",
                "image": "crops/blackpepper.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 2.0,
                "growing_time": 36,
                "min_temperature": 15.0,
                "max_temperature": 35.0,
                "min_rainfall": 2000,
                "max_rainfall": 3000,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 150,
                "max_potassium": 200,
                "min_ph": 5.5,
                "max_ph": 6.5,
                "care_tips": "Needs support trees, regular pruning essential.",
                "fertilizers": "10kg FYM + 500g NPK 12-12-17 per vine annually",
                "pesticides": "Bordeaux mixture for quick wilt, Monocrotophos for pollu beetle"
            },
            {
                "name": "bottlegourd",
                "description": "A hydrating and low-calorie vegetable ideal for hot climates, often used in soups and stews.",
                "image": "crops/bottlegourd.jpg",
                "growing_season": "Summer",
                "average_yield": 25.0,
                "growing_time": 3,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 500,
                "max_rainfall": 1500,
                "min_nitrogen": 80,
                "max_nitrogen": 120,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 60,
                "max_potassium": 100,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Needs strong trellis, harvest when fruits are tender.",
                "fertilizers": "50:50:50 NPK per plant + 10kg FYM",
                "pesticides": "Carbaryl for fruit flies, Neem oil for aphids"
            },
            {
                "name": "brinjal",
                "description": "Also known as eggplant, this glossy purple vegetable is a staple in many global cuisines.",
                "image": "crops/brinjal.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 25.0,
                "growing_time": 4,
                "min_temperature": 18.0,
                "max_temperature": 32.0,
                "min_rainfall": 600,
                "max_rainfall": 1200,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 80,
                "max_potassium": 120,
                "min_ph": 5.5,
                "max_ph": 6.5,
                "care_tips": "Staking prevents fruit rot, regular picking extends harvest.",
                "fertilizers": "150:100:100 kg NPK/ha + 25t FYM",
                "pesticides": "Chlorantraniliprole for fruit borer, Imidacloprid for whiteflies"
            },
            {
                "name": "cabbage",
                "description": "A leafy green vegetable rich in vitamins K and C, used in salads, stir-fries and pickling.",
                "image": "crops/cabbage.jpg",
                "growing_season": "Cool season",
                "average_yield": 40.0,
                "growing_time": 3,
                "min_temperature": 4.0,
                "max_temperature": 24.0,
                "min_rainfall": 350,
                "max_rainfall": 500,
                "min_nitrogen": 150,
                "max_nitrogen": 200,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 100,
                "max_potassium": 150,
                "min_ph": 6.0,
                "max_ph": 6.8,
                "care_tips": "Needs consistent moisture, avoid water stress.",
                "fertilizers": "120:60:80 kg NPK/ha + 20t FYM",
                "pesticides": "Spinosad for diamondback moth, Bacillus thuringiensis for caterpillars"
            },
            {
                "name": "cardamom",
                "description": "A fragrant spice often called the 'Queen of Spices', used in desserts and aromatic dishes.",
                "image": "crops/cardamom.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 0.15,
                "growing_time": 36,
                "min_temperature": 10.0,
                "max_temperature": 35.0,
                "min_rainfall": 1500,
                "max_rainfall": 4000,
                "min_nitrogen": 75,
                "max_nitrogen": 100,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 120,
                "max_potassium": 150,
                "min_ph": 5.0,
                "max_ph": 6.5,
                "care_tips": "Requires shade (50-70%) and high humidity.",
                "fertilizers": "75:75:150 kg NPK/ha + 5kg neem cake per plant",
                "pesticides": "Carbendazim for capsule rot, Quinalphos for shoot borer"
            },
            
            {
                "name": "cauliflower",
                "description": "A cruciferous vegetable known for its white florets, packed with antioxidants and fiber.",
                "image": "crops/cauliflower.jpg",
                "growing_season": "Cool season",
                "average_yield": 20.0,
                "growing_time": 3,
                "min_temperature": 5.0,
                "max_temperature": 25.0,
                "min_rainfall": 350,
                "max_rainfall": 500,
                "min_nitrogen": 150,
                "max_nitrogen": 200,
                "min_phosphorus": 80,
                "max_phosphorus": 100,
                "min_potassium": 100,
                "max_potassium": 150,
                "min_ph": 5.5,
                "max_ph": 6.5,
                "care_tips": "Blanching (tying leaves over curd) improves quality.",
                "fertilizers": "150:100:120 kg NPK/ha + 25t FYM",
                "pesticides": "Malathion for aphids, Cypermethrin for caterpillars"
            },

            {
                "name": "coriander",
                "description": "A herb grown for both its leaves and seeds, offering distinct flavor and health benefits.",
                "image": "crops/coriander.jpg",
                "growing_season": "Cool season",
                "average_yield": 5.0,
                "growing_time": 2,
                "min_temperature": 10.0,
                "max_temperature": 25.0,
                "min_rainfall": 300,
                "max_rainfall": 600,
                "min_nitrogen": 50,
                "max_nitrogen": 80,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 40,
                "max_potassium": 60,
                "min_ph": 6.2,
                "max_ph": 7.0,
                "care_tips": "Quick-growing, successive planting ensures continuous harvest.",
                "fertilizers": "20:20:20 NPK kg/ha + 10t FYM",
                "pesticides": "Neem oil for aphids, Carbendazim for powdery mildew"
            },
            {
                "name": "cotton",
                "description": "A major cash crop grown for its soft fibers used in textile manufacturing around the world.",
                "image": "crops/cotton.jpg",
                "growing_season": "Summer",
                "average_yield": 2.5,
                "growing_time": 6,
                "min_temperature": 21.0,
                "max_temperature": 38.0,
                "min_rainfall": 500,
                "max_rainfall": 1000,
                "min_nitrogen": 80,
                "max_nitrogen": 120,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 50,
                "max_potassium": 80,
                "min_ph": 5.8,
                "max_ph": 7.0,
                "care_tips": "Requires careful water management during boll formation.",
                "fertilizers": "60:30:30 kg NPK/ha + 5t FYM (adjust based on soil test)",
                "pesticides": "Acephate for bollworms, Spiromesifen for whiteflies"
            },
            {
                "name": "cucumber",
                "description": "A refreshing, water-rich vegetable eaten raw in salads or juiced for hydration.",
                "image": "crops/cucumber.jpg",
                "growing_season": "Summer",
                "average_yield": 20.0,
                "growing_time": 2,
                "min_temperature": 18.0,
                "max_temperature": 32.0,
                "min_rainfall": 400,
                "max_rainfall": 800,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 80,
                "max_potassium": 120,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Trellising improves yield and reduces disease.",
                "fertilizers": "100:50:50 kg NPK/ha + 20t compost",
                "pesticides": "Carbaryl for beetles, Copper fungicide for downy mildew"
            },
            {
                "name": "drumstick",
                "description": "A nutrient-dense vegetable also known as moringa, praised for its medicinal properties.",
                "image": "crops/drumstick.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 15.0,
                "growing_time": 8,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 500,
                "max_rainfall": 1500,
                "min_nitrogen": 50,
                "max_nitrogen": 80,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 40,
                "max_potassium": 70,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Prune to 1m height to encourage branching.",
                "fertilizers": "25:25:25 g NPK/plant + 10kg compost every 6 months",
                "pesticides": "Neem oil for leaf caterpillars, Carbofuran for root knot nematodes"
            },
            {
                "name": "garlic",
                "description": "A pungent bulbous plant used for seasoning and traditional medicine, rich in allicin.",
                "image": "crops/garlic.jpg",
                "growing_season": "Cool season",
                "average_yield": 8.0,
                "growing_time": 5,
                "min_temperature": 0.0,
                "max_temperature": 25.0,
                "min_rainfall": 300,
                "max_rainfall": 500,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 60,
                "max_phosphorus": 90,
                "min_potassium": 80,
                "max_potassium": 120,
                "min_ph": 5.8,
                "max_ph": 7.0,
                "care_tips": "Stop irrigation 2 weeks before harvest for better storage.",
                "fertilizers": "150:100:100 kg NPK/ha + 25t FYM",
                "pesticides": "Mancozeb for purple blotch, Imidacloprid for thrips"
            },
            {
                "name": "grapes",
                "description": "A juicy fruit grown in clusters, consumed fresh or used in wine and juice production.",
                "image": "crops/grapes.jpg",
                "growing_season": "Summer",
                "average_yield": 20.0,
                "growing_time": 12,
                "min_temperature": 15.0,
                "max_temperature": 35.0,
                "min_rainfall": 500,
                "max_rainfall": 900,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 150,
                "max_potassium": 200,
                "min_ph": 5.5,
                "max_ph": 7.0,
                "care_tips": "Pruning is critical for fruit production.",
                "fertilizers": "500:300:800 g NPK/vine/year + micronutrients",
                "pesticides": "Sulfur for powdery mildew, Spinosad for berry moth"
            },
            {
                "name": "horsegram",
                "description": "A hardy legume known for its drought resistance and high iron and protein content.",
                "image": "crops/horsegram.jpg",
                "growing_season": "Rainfed conditions",
                "average_yield": 0.6,
                "growing_time": 4,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 400,
                "max_rainfall": 800,
                "min_nitrogen": 20,
                "max_nitrogen": 40,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 20,
                "max_potassium": 40,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Excellent for dryland farming, minimal inputs needed.",
                "fertilizers": "Rhizobium culture + 25kg P2O5/ha",
                "pesticides": "Seed treatment with Thiram for fungal diseases"
            },
            {
                "name": "jackfruit",
                "description": "A tropical fruit known for its large size and use as a meat substitute when unripe.",
                "image": "crops/jackfruit.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 50.0,
                "growing_time": 60,
                "min_temperature": 16.0,
                "max_temperature": 35.0,
                "min_rainfall": 1000,
                "max_rainfall": 2400,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 100,
                "max_potassium": 150,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Space trees 10-12m apart, mulch heavily.",
                "fertilizers": "1kg FYM + 100:50:150 g NPK/tree/year (increase with age)",
                "pesticides": "Monocrotophos for fruit borer, Copper oxychloride for stem rot"
            },
            {
                "name": "jowar",
                "description": "Also called sorghum, a drought-tolerant grain used to make flatbreads and porridge.",
                "image": "crops/jowar.jpg",
                "growing_season": "Rainy season",
                "average_yield": 2.0,
                "growing_time": 4,
                "min_temperature": 18.0,
                "max_temperature": 38.0,
                "min_rainfall": 400,
                "max_rainfall": 800,
                "min_nitrogen": 60,
                "max_nitrogen": 100,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 40,
                "max_potassium": 60,
                "min_ph": 5.5,
                "max_ph": 8.4,
                "care_tips": "Very drought resistant, good for marginal soils.",
                "fertilizers": "80:40:40 kg NPK/ha (adjust N based on previous crop)",
                "pesticides": "Endosulfan for shoot fly, Mancozeb for grain mold"
            },
            {
                "name": "jute",
                "description": "A fiber crop grown for making sacks, ropes, and eco-friendly textiles.",
                "image": "crops/jute.jpg",
                "growing_season": "Summer",
                "average_yield": 2.5,
                "growing_time": 4,
                "min_temperature": 24.0,
                "max_temperature": 37.0,
                "min_rainfall": 1000,
                "max_rainfall": 2500,
                "min_nitrogen": 60,
                "max_nitrogen": 100,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 50,
                "max_potassium": 80,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Retting process crucial for fiber quality.",
                "fertilizers": "40:20:20 kg NPK/ha + 5t FYM",
                "pesticides": "Carbendazim for stem rot, Quinalphos for semilooper"
            },
            {
                "name": "ladyfinger",
                "description": "Also known as okra, this green pod vegetable is rich in fiber and essential nutrients.",
                "image": "crops/ladyfinger.jpg",
                "growing_season": "Summer",
                "average_yield": 12.0,
                "growing_time": 2,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 500,
                "max_rainfall": 1200,
                "min_nitrogen": 80,
                "max_nitrogen": 120,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 50,
                "max_potassium": 80,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Harvest pods when tender (4-5 days after flowering).",
                "fertilizers": "100:50:50 kg NPK/ha + 15t FYM",
                "pesticides": "Neem oil for fruit borers, Carbendazim for yellow vein mosaic"
            },
            {
                "name": "maize",
                "description": "A globally important cereal crop used for food, feed, and industrial products.",
                "image": "crops/maize.jpg",
                "growing_season": "Summer",
                "average_yield": 5.0,
                "growing_time": 3,
                "min_temperature": 18.0,
                "max_temperature": 32.0,
                "min_rainfall": 500,
                "max_rainfall": 1000,
                "min_nitrogen": 120,
                "max_nitrogen": 180,
                "min_phosphorus": 60,
                "max_phosphorus": 90,
                "min_potassium": 60,
                "max_potassium": 100,
                "min_ph": 5.8,
                "max_ph": 7.5,
                "care_tips": "Critical irrigation at tasseling and silking stages.",
                "fertilizers": "120:60:60 kg NPK/ha + 25t FYM",
                "pesticides": "Atrazine for weeds, Carbaryl for stem borer"
            },
            {
                "name": "mango",
                "description": "The 'king of fruits', enjoyed for its sweet flavor and rich vitamin A and C content.",
                "image": "crops/mango.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 10.0,
                "growing_time": 48,
                "min_temperature": 10.0,
                "max_temperature": 45.0,
                "min_rainfall": 750,
                "max_rainfall": 2500,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 150,
                "max_potassium": 200,
                "min_ph": 5.5,
                "max_ph": 7.5,
                "care_tips": "Prune after harvest, regulate flowering for consistent yields.",
                "fertilizers": "1kg FYM + 500:250:500 g NPK/tree/year (increase with age)",
                "pesticides": "Carbaryl for fruit fly, Copper fungicide for anthracnose"
            },
            {
                "name": "moong",
                "description": "A highly nutritious legume used in soups and salads, known for its quick cooking and digestibility.",
                "image": "crops/moong.jpg",
                "growing_season": "Summer/Kharif",
                "average_yield": 0.8,
                "growing_time": 3,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 500,
                "max_rainfall": 800,
                "min_nitrogen": 20,
                "max_nitrogen": 40,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 20,
                "max_potassium": 40,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Short duration crop, good for intercropping.",
                "fertilizers": "Rhizobium culture + 20kg P2O5/ha",
                "pesticides": "Carbendazim for root rot, Dimethoate for whitefly"
            },
            {
                "name": "onion",
                "description": "A bulb crop with strong flavor, used as a base in countless recipes worldwide.",
                "image": "crops/onion.jpg",
                "growing_season": "Cool season",
                "average_yield": 25.0,
                "growing_time": 4,
                "min_temperature": 13.0,
                "max_temperature": 30.0,
                "min_rainfall": 350,
                "max_rainfall": 750,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 80,
                "max_potassium": 120,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Stop irrigation when necks start softening before harvest.",
                "fertilizers": "120:60:60 kg NPK/ha + 25t FYM",
                "pesticides": "Mancozeb for purple blotch, Chlorpyriphos for thrips"
            },
            {
                "name": "orange",
                "description": "A citrus fruit high in vitamin C, consumed fresh or as juice to boost immunity.",
                "image": "crops/orange.jpg",
                "growing_season": "Year-round in subtropics",
                "average_yield": 15.0,
                "growing_time": 36,
                "min_temperature": 13.0,
                "max_temperature": 37.0,
                "min_rainfall": 900,
                "max_rainfall": 1800,
                "min_nitrogen": 150,
                "max_nitrogen": 200,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 200,
                "max_potassium": 250,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Requires micronutrients (Zn, Mn, Fe) for good yields.",
                "fertilizers": "600:300:300 g NPK/tree/year + 10kg FYM",
                "pesticides": "Imidacloprid for citrus psylla, Copper fungicide for canker"
            },
            {
                "name": "papaya",
                "description": "A tropical fruit known for its digestive enzymes and antioxidant-rich orange flesh.",
                "image": "crops/papaya.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 40.0,
                "growing_time": 12,
                "min_temperature": 16.0,
                "max_temperature": 35.0,
                "min_rainfall": 1000,
                "max_rainfall": 2000,
                "min_nitrogen": 150,
                "max_nitrogen": 200,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 150,
                "max_potassium": 200,
                "min_ph": 6.0,
                "max_ph": 6.5,
                "care_tips": "Plant both male and female trees for pollination.",
                "fertilizers": "200:200:200 g NPK/plant every 2 months",
                "pesticides": "Carbaryl for fruit fly, Metalaxyl for root rot"
            },
            {
                "name": "pineapple",
                "description": "A spiky tropical fruit with sweet and tart flesh, used in juices, desserts and cooking.",
                "image": "crops/pineapple.jpg",
                "growing_season": "Year-round in tropics",
                "average_yield": 50.0,
                "growing_time": 18,
                "min_temperature": 15.0,
                "max_temperature": 35.0,
                "min_rainfall": 1000,
                "max_rainfall": 1500,
                "min_nitrogen": 120,
                "max_nitrogen": 180,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 200,
                "max_potassium": 250,
                "min_ph": 4.5,
                "max_ph": 6.0,
                "care_tips": "Ethylene treatment induces uniform flowering.",
                "fertilizers": "12:4:20 NPK g/plant/month + foliar micronutrients",
                "pesticides": "Chlorpyrifos for mealybugs, Mancozeb for fruit rot"
            },
            {
                "name": "potato",
                "description": "A root crop that serves as a global staple, used in countless forms from fries to curries.",
                "image": "crops/potato.jpg",
                "growing_season": "Cool season",
                "average_yield": 25.0,
                "growing_time": 3,
                "min_temperature": 10.0,
                "max_temperature": 25.0,
                "min_rainfall": 500,
                "max_rainfall": 700,
                "min_nitrogen": 120,
                "max_nitrogen": 180,
                "min_phosphorus": 80,
                "max_phosphorus": 120,
                "min_potassium": 150,
                "max_potassium": 200,
                "min_ph": 5.0,
                "max_ph": 6.5,
                "care_tips": "Hilling up soil around plants increases tuber yield.",
                "fertilizers": "150:100:150 kg NPK/ha + 25t FYM",
                "pesticides": "Mancozeb for late blight, Imidacloprid for aphids"
            },
            {
                "name": "pumpkin",
                "description": "A large orange fruit used in pies and soups, rich in beta-carotene and fiber.",
                "image": "crops/pumpkin.jpg",
                "growing_season": "Summer",
                "average_yield": 20.0,
                "growing_time": 4,
                "min_temperature": 18.0,
                "max_temperature": 30.0,
                "min_rainfall": 500,
                "max_rainfall": 1000,
                "min_nitrogen": 80,
                "max_nitrogen": 120,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 100,
                "max_potassium": 150,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Allow fruits to mature fully on vine for best flavor.",
                "fertilizers": "100:50:100 kg NPK/ha + 20t FYM",
                "pesticides": "Carbaryl for fruit flies, Sulfur for powdery mildew"
            },
            {
                "name": "radish",
                "description": "A fast-growing root vegetable with a spicy crunch, eaten raw or cooked.",
                "image": "crops/radish.jpg",
                "growing_season": "Cool season",
                "average_yield": 15.0,
                "growing_time": 1,
                "min_temperature": 10.0,
                "max_temperature": 25.0,
                "min_rainfall": 300,
                "max_rainfall": 500,
                "min_nitrogen": 60,
                "max_nitrogen": 100,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 50,
                "max_potassium": 80,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Quick maturing, successive planting possible.",
                "fertilizers": "50:50:50 kg NPK/ha + 15t FYM",
                "pesticides": "Malathion for flea beetles, Chlorothalonil for leaf spot"
            },
            {
                "name": "ragi",
                "description": "Also called finger millet, a nutritious grain rich in calcium and used in traditional porridges.",
                "image": "crops/ragi.jpg",
                "growing_season": "Rainy season",
                "average_yield": 1.5,
                "growing_time": 4,
                "min_temperature": 18.0,
                "max_temperature": 30.0,
                "min_rainfall": 500,
                "max_rainfall": 1000,
                "min_nitrogen": 40,
                "max_nitrogen": 60,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 30,
                "max_potassium": 50,
                "min_ph": 5.0,
                "max_ph": 8.0,
                "care_tips": "Drought resistant, stores well for years.",
                "fertilizers": "40:20:20 kg NPK/ha + 5t FYM",
                "pesticides": "Seed treatment with Thiram, Endosulfan for shoot fly"
            },
            {
                "name": "rapeseed",
                "description": "A bright yellow flowering plant grown for oil-rich seeds, processed into canola oil.",
                "image": "crops/rapeseed.jpg",
                "growing_season": "Winter",
                "average_yield": 2.0,
                "growing_time": 5,
                "min_temperature": 5.0,
                "max_temperature": 25.0,
                "min_rainfall": 500,
                "max_rainfall": 800,
                "min_nitrogen": 100,
                "max_nitrogen": 150,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 60,
                "max_potassium": 100,
                "min_ph": 5.5,
                "max_ph": 7.5,
                "care_tips": "Critical irrigation at flowering and pod formation.",
                "fertilizers": "80:40:40 kg NPK/ha + 10t FYM",
                "pesticides": "Carbendazim for white rust, Deltamethrin for aphids"
            },
            {
                "name": "rice",
                "description": "The most widely consumed staple food globally, grown in flooded paddies.",
                "image": "crops/rice.jpg",
                "growing_season": "Wet season",
                "average_yield": 4.0,
                "growing_time": 5,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 1000,
                "max_rainfall": 2500,
                "min_nitrogen": 100,
                "max_nitrogen": 200,
                "min_phosphorus": 30,
                "max_phosphorus": 50,
                "min_potassium": 50,
                "max_potassium": 100,
                "min_ph": 5.0,
                "max_ph": 7.5,
                "care_tips": "Requires consistent water supply, proper leveling of fields.",
                "fertilizers": "120:60:60 kg NPK/ha (split application of N)",
                "pesticides": "Carbofuran for stem borer, Tricyclazole for blast"
            },
            {
                "name": "soyabean",
                "description": "A protein-packed legume used in tofu, oil, and animal feed, vital in vegetarian diets.",
                "image": "crops/soyabean.jpg",
                "growing_season": "Summer",
                "average_yield": 2.0,
                "growing_time": 4,
                "min_temperature": 15.0,
                "max_temperature": 35.0,
                "min_rainfall": 500,
                "max_rainfall": 1000,
                "min_nitrogen": 20,
                "max_nitrogen": 40,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 40,
                "max_potassium": 60,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Inoculate seeds with Bradyrhizobium for better N fixation.",
                "fertilizers": "20:60:40 kg NPK/ha + 5t FYM",
                "pesticides": "Chlorpyriphos for girdle beetle, Carbendazim for yellow mosaic"
            },
            {
                "name": "sunflower",
                "description": "A tall crop grown for seeds that produce oil and snacks, also ornamental.",
                "image": "crops/sunflower.jpg",
                "growing_season": "Summer",
                "average_yield": 1.5,
                "growing_time": 3,
                "min_temperature": 15.0,
                "max_temperature": 35.0,
                "min_rainfall": 500,
                "max_rainfall": 1000,
                "min_nitrogen": 80,
                "max_nitrogen": 120,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 40,
                "max_potassium": 80,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Critical irrigation at flowering and seed filling stages.",
                "fertilizers": "60:40:40 kg NPK/ha + 5t FYM",
                "pesticides": "Imidacloprid for capitulum borer, Mancozeb for rust"
            },
            {
                "name": "sweetpotato",
                "description": "A nutritious tuber rich in fiber and beta-carotene, used in both sweet and savory dishes.",
                "image": "crops/sweetpotato.jpg",
                "growing_season": "Summer",
                "average_yield": 15.0,
                "growing_time": 4,
                "min_temperature": 18.0,
                "max_temperature": 35.0,
                "min_rainfall": 750,
                "max_rainfall": 1250,
                "min_nitrogen": 50,
                "max_nitrogen": 80,
                "min_phosphorus": 40,
                "max_phosphorus": 60,
                "min_potassium": 100,
                "max_potassium": 150,
                "min_ph": 5.5,
                "max_ph": 6.5,
                "care_tips": "Vines root easily at nodes, can be propagated from cuttings.",
                "fertilizers": "50:50:100 kg NPK/ha + 20t FYM",
                "pesticides": "Chlorpyriphos for weevils, Mancozeb for leaf spot"
            },
            {
                "name": "tomato",
                "description": "A juicy red fruit used in sauces, salads, and cooking, rich in lycopene.",
                "image": "crops/tomato.jpg",
                "growing_season": "Cool season in tropics, summer in temperate",
                "average_yield": 30.0,
                "growing_time": 3,
                "min_temperature": 15.0,
                "max_temperature": 30.0,
                "min_rainfall": 600,
                "max_rainfall": 900,
                "min_nitrogen": 120,
                "max_nitrogen": 180,
                "min_phosphorus": 60,
                "max_phosphorus": 100,
                "min_potassium": 150,
                "max_potassium": 200,
                "min_ph": 6.0,
                "max_ph": 7.0,
                "care_tips": "Staking improves yield and reduces disease incidence.",
                "fertilizers": "150:100:150 kg NPK/ha + 25t FYM",
                "pesticides": "Indoxacarb for fruit borer, Metalaxyl for late blight"
            },
            {
                "name": "turmeric",
                "description": "A golden-yellow root known for its anti-inflammatory properties and use in curries.",
                "image": "crops/turmeric.jpg",
                "growing_season": "Summer",
                "average_yield": 20.0,
                "growing_time": 8,
                "min_temperature": 20.0,
                "max_temperature": 35.0,
                "min_rainfall": 1000,
                "max_rainfall": 2000,
                "min_nitrogen": 120,
                "max_nitrogen": 180,
                "min_phosphorus": 50,
                "max_phosphorus": 80,
                "min_potassium": 150,
                "max_potassium": 200,
                "min_ph": 5.5,
                "max_ph": 7.5,
                "care_tips": "Rhizomes are boiled and dried before marketing.",
                "fertilizers": "120:60:120 kg NPK/ha + 25t FYM",
                "pesticides": "Mancozeb for leaf blotch, Chlorpyriphos for shoot borer"
            },
            {
                "name": "wheat",
                "description": "A staple grain milled into flour, forming the basis of bread, pasta, and many baked goods.",
                "image": "crops/wheat.jpg",
                "growing_season": "Winter",
                "average_yield": 3.5,
                "growing_time": 5,
                "min_temperature": 10.0,
                "max_temperature": 25.0,
                "min_rainfall": 500,
                "max_rainfall": 800,
                "min_nitrogen": 120,
                "max_nitrogen": 180,
                "min_phosphorus": 60,
                "max_phosphorus": 90,
                "min_potassium": 60,
                "max_potassium": 100,
                "min_ph": 6.0,
                "max_ph": 7.5,
                "care_tips": "Critical irrigation at crown root initiation and flowering.",
                "fertilizers": "120:60:40 kg NPK/ha + 10t FYM",
                "pesticides": "Tebuconazole for rust, Chlorpyriphos for termites"
            }
        ]


        # Counter for created/updated crops
        created_count = 0
        updated_count = 0

        for crop_data in crops_data:
            crop, created = Crop.objects.update_or_create(
                name=crop_data["name"].lower(),
                defaults=crop_data
            )
            if created:
                created_count += 1

            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully added {created_count} new crops and updated {updated_count} existing crops'
            )
        )

